sudo: false
language: node_js

before_install:
 - chmod +x ./scripts/*
 - ./scripts/before_install.sh

script: ./scripts/build.sh

after_success:
 - ./scripts/after_success.sh
after_failure:
- ./scripts/after_failure.sh

env:
  global:
    - VARIABLE_NAME=value- IFTTT_KEY=tE_SGEl4AVkA__BfgFaho
